# ARM Template What-If pipeline using complete mode. WARNING This CAN remove any resources that are not defined in the template from the target resource group.
# This is a multistage pipeline and will support approvals set at the environment level in Azure DevOps.
# $(VAR) denotes variables within a variable group attached to the pipeline.

trigger:
- "*"

stages:
  - stage: Preview
    jobs:
      - job: 'Preview'
        displayName: Preview Changes
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate ARM
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'YOUR SERVICE CONNECTION'
            subscriptionId: $(subscription-id)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(resource-group)
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/YOUR DIRECTORY/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/YOUR DIRECTORY/azuredeploy.parameters.json'
            deploymentMode: 'Validation'
            deploymentName: 'SOLUTION'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'Install-Module -Name Az.Resources -Force -Scope CurrentUser'
        - task: AzurePowerShell@5
          displayName: What-If Results
          inputs:
            azureSubscription: 'YOUR SERVICE CONNECTION'
            ScriptType: 'InlineScript'
            Inline: |
              $Parameters = @{
                ResourcegroupName     = "$(resource-group)"
                Templatefile          = ".\YOUR DIRECTORY\azuredeploy.json"
                TemplateParameterfile = ".\YOUR DIRECTORY\azuredeploy.parameters.json"
                Mode                  = 'Complete'
              }
              $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
              $Result
            azurePowerShellVersion: 'LatestVersion'
  - stage: Deploy
    condition:
      and(
      succeeded(), 
      eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    dependsOn: Preview
    jobs:
      - job: "Deploy"
        displayName: Deploy Changes
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Deploy ARM
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'YOUR SERVICE CONNECTION'
            subscriptionId: $(subscription-id)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(resource-group)
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/YOUR DIRECTORY/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/YOUR DIRECTORY/azuredeploy.parameters.json'
            deploymentMode: 'Complete'
            deploymentName: 'SOLUTION'
      - deployment: Dev
        pool:
          vmimage: windows-latest
        # creates an environment if it doesn’t exist
        environment: 'Dev'
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
              - script: echo Required to enable approvals
