# Previews bicep changes with what-if before deployment. You will need to manually assign an approval check to the environment to ensure stage 2 does not automatically start.

trigger:
- none

stages:
  - stage: Preview
    displayName: Preview Stage
    jobs:
    - job: 'Preview'
      displayName: Preview Changes
      pool:
        vmimage: ubuntu-latest
      steps:
      - task: AzureCLI@2
        displayName: Bicep What-if
        inputs:
          azureSubscription: '$(ServiceConnectionName)'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group what-if --name NAME --resource-group '$(ResourceGroupName)' --template-file '$(Build.SourcesDirectory)/Bicep/main.bicep' --parameters '$(Build.SourcesDirectory)/Parameters/$(ParametersFile)'

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Preview
    jobs:
    - deployment: Deploy
      displayName: Deploy Infrastructure
      pool:
        vmimage: ubuntu-latest
      # creates an environment if it doesn’t exist
      environment: '$(EnvironmentName)'
      strategy:
        # default deployment strategy
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: AzureCLI@2
              displayName: Deploy Bicep
              inputs:
                azureSubscription: '$(ServiceConnectionName)'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create --name NAME --resource-group '$(ResourceGroupName)' --template-file '$(Build.SourcesDirectory)/Bicep/main.bicep' --parameters '$(Build.SourcesDirectory)/Parameters/$(ParametersFile)'
